### ISSUE TITLE
Required node engine

### ISSUE THREAD

**Issue by ben12** [tijsverkoyen/stylelint-formatter-gitlab-code-quality-report#1]
It really require Node >= 20.10.0 ?

Stylelint require Node >= 18.12.0, [stylelint-formatter-gitlab-code-quality-report](https://github.com/tijsverkoyen/stylelint-formatter-gitlab-code-quality-report) may require the same version.

**Comment by tijsverkoyen** [comment]
@ben12 could be that it works on >= 18.12.0. I did not test it. I was using 20.10.0 on my local machine.

**Comment by ben12** [comment]
I just changed my .npmrc configuration from `engine-strict=true` to `engine-strict=false` to be able to install [stylelint-formatter-gitlab-code-quality-report](https://github.com/tijsverkoyen/stylelint-formatter-gitlab-code-quality-report)

My Node version is currently v18.16.1, it seems to work (without or with same entries in report).

It can be fine to use Github Actions to run tests with different node versions ;)

**Comment by tijsverkoyen** [comment]
Thx! merged it and created https://github.com/tijsverkoyen/stylelint-formatter-gitlab-code-quality-report/releases/tag/v1.1.0
I had mistagged the first release, so that is why it is v1.1.0
